{% set name = "pytest-verbose-parametrize" %}
{% set version = "1.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-verbose-parametrize-{{ version }}.tar.gz
  sha256: d348e4ed7cd4d76365a7d38cfd2a738fbd0db84738e9bd3a6c253ed31eb5632d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
    - setuptools-git
  run:
    - pytest
    - python >=2.7
    - six

test:
  imports:
    - pytest_verbose_parametrize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/manahl/pytest-plugins
  summary: More descriptive output for parametrized py.test tests
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
