{% set name = "pytest-verbose-parametrize" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-verbose-parametrize-{{ version }}.tar.gz
  sha256: 05dfd556c446159c366b88e196676321f48a6d92ad6465bae69758dd603db0a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
    - setuptools-git
  run:
    - pytest
    - python >=2.7
    - six

test:
  imports:
    - pytest_verbose_parametrize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/manahl/pytest-plugins
  summary: More descriptive output for parametrized py.test tests
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
